serviceAccountName: build
source:
    git:
      url: https://github.com/sebgoa/functions.git
      revision: master
steps:
- name: ls
  image: busybox
  args: ['ls']
- name: date
  image: busybox
  args: ['/bin/date']
